services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST API, http://localhost:6333/dashboard
      - "6334:6334"   # gRPC,
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - services_network

volumes:
  qdrant_data:

networks:
  services_network:
    external: true